#ifndef RETROPANASONIC_MAJOR_VERSION
#define RETROPANASONIC_MAJOR_VERSION      1      /* Major version number */
#define RETROPANASONIC_MINOR_VERSION      6      /* Minor version number */
#define RETROPANASONIC_TYPE_VERSION       0      /* 0 alpha, 1 beta, 2 release */
#define RETROPANASONIC_PATCH_VERSION      1      /* Patch level */
#define RETROPANASONIC_ALPHA_VERSION     (RETROPANASONIC_TYPE_VERSION==0)
#define RETROPANASONIC_BETA_VERSION      (RETROPANASONIC_TYPE_VERSION==1)
#define RETROPANASONIC_RELEASE_VERSION   (RETROPANASONIC_TYPE_VERSION==2)
#endif
